version: '3'

services:
  nginx-rtmp:
    build: .
    restart: unless-stopped
    ports:
      - 1935:1935
      - 80:80
      - 8443:443
      - 8080:8080
    environment:
      - HTTP_PORT=80
      - RTMP_PORT=1935
    volumes:
      - datanginx:/var/www/ustream/
      - datanginxlogs:/var/log/nginx/
      - ./conf/nginx-wp:/etc/nginx/
      - ./conf/assets/users/self:/var/www/ustream/assets/users/self 
volumes:
  datanginxlogs:
  datanginx:      